<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\ShowroomActivity;
use Illuminate\Database\Seeder;

class ShowroomPharmacyProductSeeder extends Seeder
{
    public function run(): void
    {
        $this->call(ShowroomActivitySeeder::class);

        $activities = ShowroomActivity::whereIn('slug', $this->activitySlugs())
            ->get()
            ->keyBy('slug');

        foreach ($this->products() as $index => $item) {
            $quoteOnly = $item['type'] !== 'commandable';

            $product = Product::updateOrCreate(
                ['slug' => $item['slug']],
                [
                    'category_id' => null,
                    'room_id' => null,
                    'product_type_id' => null,
                    'primary_collection_id' => null,
                    'title' => $item['title'],
                    'price_millimes' => $this->price($item['price'] ?? null),
                    'compare_at_millimes' => $this->price($item['compare_at'] ?? null),
                    'stock' => $quoteOnly ? 0 : 10,
                    'sku' => null,
                    'brand' => null,
                    'sale_mode' => $quoteOnly ? 'sur_mesure' : 'catalog',
                    'quote_only' => $quoteOnly,
                    'is_starting_price' => (bool) ($item['starting_price'] ?? false),
                    'is_customizable' => $quoteOnly || !empty($item['options']),
                    'showroom_badge' => $item['badge'],
                    'main_image' => null,
                    'material_summary' => $item['materials'],
                    'dimension_summary' => $item['dimensions'],
                    'availability_label' => $item['availability'],
                    'delivery_note' => $item['delivery'],
                    'finish_summary' => $item['finishes'],
                    'short_description' => $item['short_description'],
                    'long_description' => $item['long_description'],
                    'attributes' => null,
                    'custom_options' => $item['options'],
                    'is_active' => true,
                ]
            );

            $payload = [];
            foreach ($item['activities'] as $activitySlug) {
                if (!$activities->has($activitySlug)) {
                    continue;
                }

                $payload[$activities[$activitySlug]->id] = [
                    'sort_order' => $activitySlug === 'pharmacies-parapharmacies' ? $index + 1 : 1000 + $index,
                ];
            }

            $product->showroomActivities()->sync($payload);
            $product->images()->delete();
        }
    }

    private function price(?int $dinars): ?int
    {
        return $dinars === null ? null : $dinars * 1000;
    }

    /**
     * @return array<int, string>
     */
    private function activitySlugs(): array
    {
        return [
            'pharmacies-parapharmacies',
            'salons-beaute-esthetique',
            'boutiques-magasins',
            'cabinets-medicaux-cliniques',
            'bureaux-professionnels',
        ];
    }

    /**
     * Products with an indicative price but custom dimensions are seeded as
     * quote products. The admin keeps only two sale types: commandable or sur devis.
     *
     * @return array<int, array<string, mixed>>
     */
    private function products(): array
    {
        return [
            [
                'title' => 'Comptoir parapharmacie compact',
                'slug' => 'comptoir-parapharmacie-compact',
                'type' => 'quote',
                'badge' => 'Standard, Sur mesure, Pro',
                'price' => 1250,
                'compare_at' => 1490,
                'starting_price' => true,
                'availability' => 'Sur commande',
                'delivery' => 'Grand Tunis, pose sur devis',
                'activities' => ['pharmacies-parapharmacies'],
                'materials' => 'MDF, bois mélaminé, aluminium, métal',
                'dimensions' => '120 x 60 x 110 cm',
                'finishes' => 'Blanc mat, chêne clair, noir mat, RAL au choix',
                'short_description' => 'Comptoir compact pour parapharmacie, pharmacie ou espace beauté, adapté aux petits locaux et aux zones d’accueil.',
                'long_description' => 'Ce comptoir compact est conçu pour les parapharmacies, pharmacies, boutiques cosmétiques et espaces de vente santé/beauté qui souhaitent un point d’accueil propre, fonctionnel et professionnel. Il peut être adapté aux dimensions du local, avec plusieurs choix de finitions, rangements, éclairage ou intégration de logo.',
                'options' => [
                    'Dimensions' => ['120 cm', '150 cm', '180 cm', 'Sur mesure'],
                    'Finitions' => ['Blanc mat', 'Chêne clair', 'Noir mat', 'RAL au choix'],
                    'Options' => ['Tiroirs', 'Rangement intérieur', 'Logo en façade', 'LED', 'Passe-câbles'],
                    'Pose' => ['Sans pose', 'Pose sur devis'],
                ],
            ],
            [
                'title' => 'Comptoir parapharmacie premium avec logo',
                'slug' => 'comptoir-parapharmacie-premium-logo',
                'type' => 'quote',
                'badge' => 'Premium, Sur mesure, Pro',
                'price' => null,
                'compare_at' => null,
                'starting_price' => false,
                'availability' => 'Sur commande',
                'delivery' => 'Livraison et pose sur devis',
                'activities' => ['pharmacies-parapharmacies'],
                'materials' => 'MDF laqué, bois, aluminium, métal, LED',
                'dimensions' => 'Sur mesure',
                'finishes' => 'Blanc, bois naturel, vert pharmacie, noir mat, RAL au choix',
                'short_description' => 'Comptoir premium sur mesure avec habillage logo, éclairage et rangements intégrés pour pharmacies et parapharmacies.',
                'long_description' => 'Ce comptoir premium est pensé pour les pharmacies et parapharmacies qui veulent un espace d’accueil plus haut de gamme. Il peut intégrer un logo en façade, un éclairage LED, des rangements intérieurs, une zone caisse, une zone conseil et des finitions adaptées à l’identité du point de vente.',
                'options' => [
                    'Dimensions' => ['Sur mesure'],
                    'Finitions' => ['Blanc brillant', 'Blanc mat', 'Chêne clair', 'Noir mat', 'RAL au choix'],
                    'Options' => ['Logo découpé', 'Logo lumineux', 'LED basse', 'Tiroirs', 'Placards', 'Zone caisse', 'Plan de travail renforcé'],
                    'Usage' => ['Pharmacie', 'Parapharmacie', 'Boutique cosmétique', 'Espace conseil'],
                ],
            ],
            [
                'title' => 'Présentoir mural parapharmacie',
                'slug' => 'presentoir-mural-parapharmacie',
                'type' => 'quote',
                'badge' => 'Standard, Sur mesure',
                'price' => 680,
                'compare_at' => 790,
                'starting_price' => true,
                'availability' => 'Sur commande',
                'delivery' => 'Grand Tunis, pose sur devis',
                'activities' => ['pharmacies-parapharmacies'],
                'materials' => 'MDF, bois mélaminé, métal, verre optionnel',
                'dimensions' => '100 x 30 x 220 cm',
                'finishes' => 'Blanc, bois clair, noir, RAL au choix',
                'short_description' => 'Présentoir mural pour produits de parapharmacie, cosmétiques, compléments, soins visage ou produits bébé.',
                'long_description' => 'Ce présentoir mural permet d’exposer les produits de parapharmacie de façon claire et organisée. Il peut être utilisé pour les gammes cosmétiques, les produits bébé, les compléments alimentaires, les soins capillaires ou les produits promotionnels. Les dimensions, couleurs et niveaux d’étagères peuvent être adaptés au local.',
                'options' => [
                    'Largeur' => ['80 cm', '100 cm', '120 cm', 'Sur mesure'],
                    'Hauteur' => ['200 cm', '220 cm', '240 cm', 'Sur mesure'],
                    'Options' => ['Étagères réglables', 'Fond décoratif', 'Éclairage LED', 'Bandeau marque', 'Verre de protection'],
                    'Finitions' => ['Blanc', 'Chêne clair', 'Noir', 'RAL au choix'],
                ],
            ],
            [
                'title' => 'Gondole centrale parapharmacie',
                'slug' => 'gondole-centrale-parapharmacie',
                'type' => 'quote',
                'badge' => 'Standard, Pro, Sur mesure',
                'price' => 950,
                'compare_at' => 1150,
                'starting_price' => true,
                'availability' => 'Sur commande',
                'delivery' => 'Livraison et pose sur devis',
                'activities' => ['pharmacies-parapharmacies'],
                'materials' => 'MDF, métal, bois mélaminé',
                'dimensions' => '120 x 60 x 140 cm',
                'finishes' => 'Blanc, bois clair, gris, RAL au choix',
                'short_description' => 'Gondole centrale double face pour exposer les produits de parapharmacie au centre du point de vente.',
                'long_description' => 'La gondole centrale permet d’optimiser la circulation et la mise en avant des produits à forte rotation. Elle est adaptée aux promotions, soins visage, produits bébé, compléments alimentaires, accessoires santé ou produits saisonniers. Elle peut être fabriquée en plusieurs dimensions selon l’espace disponible.',
                'options' => [
                    'Dimensions' => ['100 x 50 cm', '120 x 60 cm', '150 x 70 cm', 'Sur mesure'],
                    'Faces' => ['Simple face', 'Double face'],
                    'Options' => ['Étagères réglables', 'Roulettes', 'Bandeau promotion', 'LED', 'Logo'],
                    'Finitions' => ['Blanc', 'Chêne clair', 'Gris', 'RAL au choix'],
                ],
            ],
            [
                'title' => 'Meuble arrière-comptoir pharmacie',
                'slug' => 'meuble-arriere-comptoir-pharmacie',
                'type' => 'quote',
                'badge' => 'Sur mesure, Pro',
                'price' => null,
                'compare_at' => null,
                'starting_price' => false,
                'availability' => 'Sur commande',
                'delivery' => 'Livraison et pose sur devis',
                'activities' => ['pharmacies-parapharmacies'],
                'materials' => 'MDF, bois mélaminé, aluminium, métal',
                'dimensions' => 'Sur mesure',
                'finishes' => 'Blanc, bois clair, gris, RAL au choix',
                'short_description' => 'Meuble arrière-comptoir pour organiser les produits, documents, caisses, sacs et accessoires de vente.',
                'long_description' => 'Ce meuble arrière-comptoir est conçu pour structurer l’espace de travail derrière le comptoir. Il peut intégrer des placards, tiroirs, niches ouvertes, étagères, espace imprimante, zone sacs, rangement documents et éléments techniques. Il est fabriqué selon la configuration du local et le fonctionnement de l’équipe.',
                'options' => [
                    'Configuration' => ['Placards', 'Tiroirs', 'Niches ouvertes', 'Étagères', 'Mixte'],
                    'Options' => ['Espace imprimante', 'Rangement sacs', 'Zone documents', 'LED', 'Serrures'],
                    'Dimensions' => ['Sur mesure'],
                    'Finitions' => ['Blanc', 'Chêne clair', 'Gris', 'RAL au choix'],
                ],
            ],
            [
                'title' => 'Meuble promotion central',
                'slug' => 'meuble-promotion-central-parapharmacie',
                'type' => 'quote',
                'badge' => 'Standard, Pro',
                'price' => 520,
                'compare_at' => 620,
                'starting_price' => true,
                'availability' => 'Sur commande',
                'delivery' => 'Grand Tunis, pose sur devis',
                'activities' => ['pharmacies-parapharmacies', 'boutiques-magasins'],
                'materials' => 'MDF, bois mélaminé, métal',
                'dimensions' => '90 x 60 x 90 cm',
                'finishes' => 'Blanc, bois clair, RAL au choix',
                'short_description' => 'Meuble central pour promotions, nouveautés, produits saisonniers ou offres spéciales.',
                'long_description' => 'Ce meuble promotion central est conçu pour mettre en avant des produits à forte marge ou des opérations commerciales. Il peut être placé dans l’allée centrale d’une parapharmacie, à proximité du comptoir ou à l’entrée du point de vente.',
                'options' => [
                    'Dimensions' => ['80 x 50 cm', '90 x 60 cm', '120 x 70 cm', 'Sur mesure'],
                    'Options' => ['Bac supérieur', 'Étagères latérales', 'Roulettes', 'Bandeau promotion', 'Logo'],
                    'Finitions' => ['Blanc', 'Chêne clair', 'RAL au choix'],
                ],
            ],
            [
                'title' => 'Vitrine produits cosmétiques',
                'slug' => 'vitrine-produits-cosmetiques',
                'type' => 'quote',
                'badge' => 'Premium, Standard',
                'price' => 780,
                'compare_at' => 920,
                'starting_price' => true,
                'availability' => 'Sur commande',
                'delivery' => 'Livraison et pose sur devis',
                'activities' => ['pharmacies-parapharmacies', 'salons-beaute-esthetique', 'boutiques-magasins'],
                'materials' => 'MDF, verre, aluminium, LED optionnel',
                'dimensions' => '80 x 40 x 180 cm',
                'finishes' => 'Blanc, noir, bois clair, RAL au choix',
                'short_description' => 'Vitrine verticale pour exposer les produits cosmétiques, parfums, soins premium ou gammes dermocosmétiques.',
                'long_description' => 'Cette vitrine permet de valoriser les produits à forte valeur ajoutée dans une parapharmacie ou boutique beauté. Elle peut intégrer des étagères en verre, un éclairage LED, une fermeture vitrée ou un bandeau de marque.',
                'options' => [
                    'Dimensions' => ['80 x 40 x 180 cm', '100 x 40 x 200 cm', 'Sur mesure'],
                    'Options' => ['Éclairage LED', 'Portes vitrées', 'Étagères verre', 'Serrure', 'Bandeau marque'],
                    'Finitions' => ['Blanc', 'Noir', 'Chêne clair', 'RAL au choix'],
                ],
            ],
            [
                'title' => 'Meuble dermocosmétique premium',
                'slug' => 'meuble-dermocosmetique-premium',
                'type' => 'quote',
                'badge' => 'Premium, Pro, Sur mesure',
                'price' => null,
                'compare_at' => null,
                'starting_price' => false,
                'availability' => 'Sur commande',
                'delivery' => 'Livraison et pose sur devis',
                'activities' => ['pharmacies-parapharmacies', 'salons-beaute-esthetique'],
                'materials' => 'MDF laqué, verre, aluminium, LED',
                'dimensions' => 'Sur mesure',
                'finishes' => 'Blanc premium, bois clair, noir, RAL au choix',
                'short_description' => 'Meuble premium pour gammes dermocosmétiques, soins visage et marques beauté haut de gamme.',
                'long_description' => 'Ce meuble est pensé pour valoriser les gammes dermocosmétiques dans un espace de vente structuré et premium. Il peut intégrer éclairage LED, niches produits, étagères réglables, bandeau marque, miroir, tiroirs ou zones de démonstration.',
                'options' => [
                    'Dimensions' => ['Sur mesure'],
                    'Options' => ['LED intégrée', 'Étagères verre', 'Bandeau marque', 'Miroir', 'Tiroirs', 'Niches premium', 'Logo'],
                    'Finitions' => ['Blanc premium', 'Noir mat', 'Bois clair', 'RAL au choix'],
                ],
            ],
            [
                'title' => 'Meuble caisse parapharmacie',
                'slug' => 'meuble-caisse-parapharmacie',
                'type' => 'quote',
                'badge' => 'Standard, Sur mesure',
                'price' => 650,
                'compare_at' => 790,
                'starting_price' => true,
                'availability' => 'Sur commande',
                'delivery' => 'Grand Tunis, pose sur devis',
                'activities' => ['pharmacies-parapharmacies', 'boutiques-magasins'],
                'materials' => 'MDF, bois mélaminé, métal',
                'dimensions' => '90 x 55 x 100 cm',
                'finishes' => 'Blanc, bois clair, noir mat',
                'short_description' => 'Meuble caisse compact avec espace pour caisse, imprimante, sacs et petits rangements.',
                'long_description' => 'Ce meuble caisse est conçu pour les petits espaces de vente ou les zones secondaires d’encaissement. Il peut intégrer un passage câbles, un espace imprimante, des rangements intérieurs, un tiroir caisse ou une façade personnalisée.',
                'options' => [
                    'Dimensions' => ['90 cm', '120 cm', 'Sur mesure'],
                    'Options' => ['Passe-câbles', 'Tiroir caisse', 'Rangement sacs', 'Étagère intérieure', 'Logo façade'],
                    'Finitions' => ['Blanc', 'Chêne clair', 'Noir mat'],
                ],
            ],
            [
                'title' => 'Habillage mural parapharmacie avec logo',
                'slug' => 'habillage-mural-parapharmacie-logo',
                'type' => 'quote',
                'badge' => 'Premium, Sur mesure, Pro',
                'price' => null,
                'compare_at' => null,
                'starting_price' => false,
                'availability' => 'Sur commande',
                'delivery' => 'Livraison et pose sur devis',
                'activities' => ['pharmacies-parapharmacies'],
                'materials' => 'MDF, bois, aluminium, métal, LED',
                'dimensions' => 'Sur mesure',
                'finishes' => 'RAL au choix, bois naturel, blanc, vert, noir',
                'short_description' => 'Habillage mural décoratif avec logo pour renforcer l’identité visuelle d’une pharmacie ou parapharmacie.',
                'long_description' => 'L’habillage mural permet de transformer un mur simple en espace de marque professionnel. Il peut être placé derrière le comptoir, dans la zone conseil ou sur un mur principal. Maison216 peut intégrer logo, relief, éclairage, panneaux décoratifs, niches et finitions adaptées à l’identité du commerce.',
                'options' => [
                    'Dimensions' => ['Sur mesure'],
                    'Options' => ['Logo découpé', 'Logo lumineux', 'Panneaux décoratifs', 'Niches', 'LED indirecte', 'Relief 3D'],
                    'Finitions' => ['Blanc', 'Vert pharmacie', 'Bois naturel', 'Noir', 'RAL au choix'],
                ],
            ],
            [
                'title' => 'Meuble présentoir bébé & maternité',
                'slug' => 'meuble-presentoir-bebe-maternite',
                'type' => 'quote',
                'badge' => 'Standard, Sur mesure',
                'price' => 720,
                'compare_at' => 850,
                'starting_price' => true,
                'availability' => 'Sur commande',
                'delivery' => 'Grand Tunis, pose sur devis',
                'activities' => ['pharmacies-parapharmacies'],
                'materials' => 'MDF, bois mélaminé, métal',
                'dimensions' => '100 x 35 x 180 cm',
                'finishes' => 'Blanc, bois clair, pastel, RAL au choix',
                'short_description' => 'Meuble dédié aux produits bébé, maternité, hygiène infantile et accessoires de soin.',
                'long_description' => 'Ce présentoir est conçu pour créer une zone claire dédiée aux produits bébé et maternité. Il peut accueillir couches, soins, biberons, accessoires, produits d’hygiène et articles de puériculture légère. Les couleurs et dimensions peuvent être adaptées à l’identité de la parapharmacie.',
                'options' => [
                    'Dimensions' => ['100 cm', '120 cm', 'Sur mesure'],
                    'Options' => ['Étagères réglables', 'Bandeau catégorie', 'Fond décoratif', 'LED', 'Niches'],
                    'Finitions' => ['Blanc', 'Chêne clair', 'Pastel', 'RAL au choix'],
                ],
            ],
            [
                'title' => 'Présentoir compléments alimentaires',
                'slug' => 'presentoir-complements-alimentaires',
                'type' => 'quote',
                'badge' => 'Standard, Pro',
                'price' => 590,
                'compare_at' => 690,
                'starting_price' => true,
                'availability' => 'Sur commande',
                'delivery' => 'Grand Tunis',
                'activities' => ['pharmacies-parapharmacies'],
                'materials' => 'MDF, métal, bois mélaminé',
                'dimensions' => '80 x 35 x 180 cm',
                'finishes' => 'Blanc, bois clair, noir, RAL au choix',
                'short_description' => 'Présentoir vertical pour compléments alimentaires, vitamines, produits minceur ou nutrition sportive.',
                'long_description' => 'Ce meuble permet de structurer une zone dédiée aux compléments alimentaires et produits santé. Il est adapté aux petits conditionnements, boîtes, flacons et produits à forte rotation. Il peut être personnalisé avec un bandeau catégorie ou une finition spécifique.',
                'options' => [
                    'Dimensions' => ['80 cm', '100 cm', 'Sur mesure'],
                    'Options' => ['Bandeau catégorie', 'Étagères réglables', 'Stop-rayons', 'LED', 'Fond personnalisé'],
                    'Finitions' => ['Blanc', 'Chêne clair', 'Noir', 'RAL au choix'],
                ],
            ],
            [
                'title' => 'Armoire de stockage parapharmacie',
                'slug' => 'armoire-stockage-parapharmacie',
                'type' => 'commandable',
                'badge' => 'Standard, Pro',
                'price' => 640,
                'compare_at' => 760,
                'starting_price' => false,
                'availability' => 'En stock, sur commande',
                'delivery' => 'Grand Tunis',
                'activities' => ['pharmacies-parapharmacies', 'cabinets-medicaux-cliniques'],
                'materials' => 'MDF, bois mélaminé',
                'dimensions' => '100 x 45 x 200 cm',
                'finishes' => 'Blanc, gris, bois clair',
                'short_description' => 'Armoire de rangement pour stock, produits, accessoires, documents ou consommables.',
                'long_description' => 'Cette armoire de stockage permet d’organiser les réserves et les produits non exposés. Elle convient aux parapharmacies, pharmacies, cabinets médicaux et petits espaces professionnels qui ont besoin de rangement fermé et propre.',
                'options' => [
                    'Dimensions' => ['100 x 45 x 200 cm', '120 x 45 x 220 cm', 'Sur mesure'],
                    'Options' => ['Portes battantes', 'Étagères réglables', 'Serrure', 'Tiroirs bas'],
                    'Finitions' => ['Blanc', 'Gris', 'Chêne clair'],
                ],
            ],
            [
                'title' => 'Module tiroirs arrière-comptoir',
                'slug' => 'module-tiroirs-arriere-comptoir',
                'type' => 'commandable',
                'badge' => 'Standard',
                'price' => 390,
                'compare_at' => 450,
                'starting_price' => false,
                'availability' => 'Sur commande',
                'delivery' => 'Grand Tunis',
                'activities' => ['pharmacies-parapharmacies', 'cabinets-medicaux-cliniques', 'bureaux-professionnels'],
                'materials' => 'MDF, bois mélaminé, quincaillerie métal',
                'dimensions' => '50 x 45 x 75 cm',
                'finishes' => 'Blanc, gris, bois clair',
                'short_description' => 'Module de tiroirs pour organiser petits produits, documents, accessoires ou consommables.',
                'long_description' => 'Ce module peut être placé derrière un comptoir, sous un plan de travail ou dans une zone de préparation. Il permet de ranger les petits éléments utilisés au quotidien dans une parapharmacie ou un cabinet professionnel.',
                'options' => [
                    'Dimensions' => ['50 x 45 x 75 cm', 'Sur mesure'],
                    'Options' => ['3 tiroirs', '4 tiroirs', 'Serrure', 'Roulettes'],
                    'Finitions' => ['Blanc', 'Gris', 'Chêne clair'],
                ],
            ],
            [
                'title' => 'Étagère murale produits beauté',
                'slug' => 'etagere-murale-produits-beaute',
                'type' => 'commandable',
                'badge' => 'Standard',
                'price' => 290,
                'compare_at' => 350,
                'starting_price' => false,
                'availability' => 'En stock, sur commande',
                'delivery' => 'Livraison Grand Tunis',
                'activities' => ['pharmacies-parapharmacies', 'salons-beaute-esthetique', 'boutiques-magasins'],
                'materials' => 'MDF, bois mélaminé',
                'dimensions' => '100 x 20 x 80 cm',
                'finishes' => 'Blanc, chêne clair, noir',
                'short_description' => 'Étagère murale simple pour exposer des produits cosmétiques, soins ou accessoires beauté.',
                'long_description' => 'Cette étagère murale est adaptée aux parapharmacies, boutiques beauté et salons esthétiques. Elle permet de présenter des produits légers de manière claire et accessible. Elle peut être commandée en version standard ou personnalisée selon la couleur et les dimensions souhaitées.',
                'options' => [
                    'Dimensions' => ['100 cm', '120 cm', 'Sur mesure'],
                    'Finitions' => ['Blanc', 'Chêne clair', 'Noir'],
                    'Options' => ['Avec fond', 'Sans fond', 'Bandeau marque'],
                ],
            ],
            [
                'title' => 'Présentoir comptoir petit format',
                'slug' => 'presentoir-comptoir-petit-format',
                'type' => 'commandable',
                'badge' => 'Standard',
                'price' => 120,
                'compare_at' => 150,
                'starting_price' => false,
                'availability' => 'En stock, sur commande',
                'delivery' => 'Livraison Grand Tunis',
                'activities' => ['pharmacies-parapharmacies', 'boutiques-magasins', 'salons-beaute-esthetique'],
                'materials' => 'MDF, plexi optionnel',
                'dimensions' => '40 x 25 x 45 cm',
                'finishes' => 'Blanc, bois clair, noir',
                'short_description' => 'Petit présentoir à poser sur comptoir pour promotions, petits produits ou nouveautés.',
                'long_description' => 'Ce présentoir compact est idéal pour les petits produits de parapharmacie : sticks, crèmes, accessoires, soins format voyage, promotions ou nouveautés. Il peut être utilisé sur un comptoir, une table promotionnelle ou une zone caisse.',
                'options' => [
                    'Dimensions' => ['40 x 25 x 45 cm', '60 x 30 x 50 cm'],
                    'Options' => ['Avec séparation', 'Avec bandeau marque', 'Avec plexi'],
                    'Finitions' => ['Blanc', 'Chêne clair', 'Noir'],
                ],
            ],
            [
                'title' => 'Claustra séparation zone conseil',
                'slug' => 'claustra-separation-zone-conseil-parapharmacie',
                'type' => 'quote',
                'badge' => 'Sur mesure, Premium',
                'price' => 480,
                'compare_at' => 590,
                'starting_price' => true,
                'availability' => 'Sur commande',
                'delivery' => 'Pose sur devis',
                'activities' => ['pharmacies-parapharmacies', 'cabinets-medicaux-cliniques', 'bureaux-professionnels'],
                'materials' => 'Bois, MDF, métal',
                'dimensions' => '100 x 220 cm',
                'finishes' => 'Bois naturel, blanc, noir, RAL au choix',
                'short_description' => 'Séparation décorative pour créer une zone conseil, attente ou confidentialité dans une parapharmacie.',
                'long_description' => 'Le claustra permet de structurer l’espace sans fermer complètement la circulation. Il peut servir à délimiter une zone conseil, une zone d’attente, un espace diagnostic beauté ou un coin confidentialité.',
                'options' => [
                    'Dimensions' => ['100 x 220 cm', '120 x 240 cm', 'Sur mesure'],
                    'Motifs' => ['Lignes verticales', 'Motif géométrique', 'Motif personnalisé'],
                    'Options' => ['Fixation sol/plafond', 'Structure métal', 'Logo intégré'],
                    'Finitions' => ['Bois naturel', 'Blanc', 'Noir', 'RAL au choix'],
                ],
            ],
            [
                'title' => 'Pack ouverture parapharmacie essentiel',
                'slug' => 'pack-ouverture-parapharmacie-essentiel',
                'type' => 'quote',
                'badge' => 'Pack, Pro, Sur mesure',
                'price' => null,
                'compare_at' => null,
                'starting_price' => false,
                'availability' => 'Sur commande',
                'delivery' => 'Livraison et pose sur devis',
                'activities' => ['pharmacies-parapharmacies'],
                'materials' => 'MDF, bois, aluminium, métal selon projet',
                'dimensions' => 'Selon local',
                'finishes' => 'Selon identité visuelle',
                'short_description' => 'Pack d’aménagement de base pour ouvrir une petite parapharmacie ou rénover un espace existant.',
                'long_description' => 'Le Pack ouverture parapharmacie essentiel regroupe les éléments prioritaires pour lancer ou rénover un espace de vente : comptoir, présentoirs muraux, meuble central et rangement arrière-comptoir. Il est adapté aux petits et moyens locaux et peut être ajusté selon le budget, les dimensions et l’identité visuelle du projet.',
                'options' => [
                    'Inclus' => ['Comptoir principal', 'Présentoir mural', 'Meuble central', 'Armoire arrière-comptoir'],
                    'Options' => ['Habillage logo', 'LED', 'Gondole supplémentaire', 'Meuble promotion', 'Pose complète'],
                    'Adaptation' => ['Petit local', 'Moyen local', 'Sur mesure complet'],
                ],
            ],
            [
                'title' => 'Pack parapharmacie premium',
                'slug' => 'pack-parapharmacie-premium',
                'type' => 'quote',
                'badge' => 'Pack, Premium, Sur mesure',
                'price' => null,
                'compare_at' => null,
                'starting_price' => false,
                'availability' => 'Sur commande',
                'delivery' => 'Livraison et pose sur devis',
                'activities' => ['pharmacies-parapharmacies'],
                'materials' => 'MDF laqué, bois, aluminium, métal, verre, LED',
                'dimensions' => 'Selon local',
                'finishes' => 'Selon charte et identité visuelle',
                'short_description' => 'Solution complète pour parapharmacie premium avec comptoir, présentoirs, gondoles, vitrine et habillage mural.',
                'long_description' => 'Ce pack est destiné aux parapharmacies qui veulent un espace plus structuré, plus haut de gamme et plus différenciant. Il peut inclure comptoir premium, mur d’exposition, gondoles centrales, vitrine cosmétique, meuble arrière-comptoir, habillage logo et éclairage décoratif.',
                'options' => [
                    'Inclus' => ['Comptoir premium', 'Présentoirs muraux', 'Gondoles centrales', 'Vitrine cosmétique', 'Meuble arrière-comptoir', 'Habillage mural logo'],
                    'Options' => ['Éclairage LED', 'Signalétique catégories', 'Zone bébé', 'Zone dermocosmétique', 'Zone conseil'],
                    'Niveau' => ['Premium', 'Très premium', 'Sur mesure complet'],
                ],
            ],
            [
                'title' => 'Pack rénovation pharmacie existante',
                'slug' => 'pack-renovation-pharmacie-existante',
                'type' => 'quote',
                'badge' => 'Pack, Pro, Sur mesure',
                'price' => null,
                'compare_at' => null,
                'starting_price' => false,
                'availability' => 'Sur commande',
                'delivery' => 'Livraison et pose sur devis',
                'activities' => ['pharmacies-parapharmacies'],
                'materials' => 'Selon projet',
                'dimensions' => 'Selon local',
                'finishes' => 'Selon identité existante',
                'short_description' => 'Pack pour moderniser une pharmacie ou parapharmacie déjà ouverte sans repartir de zéro.',
                'long_description' => 'Ce pack est conçu pour les pharmacies et parapharmacies qui souhaitent moderniser leur espace progressivement : remplacement du comptoir, ajout de présentoirs, création d’une zone dermocosmétique, optimisation du rangement ou habillage mural avec logo. L’objectif est d’améliorer l’image et la fonctionnalité sans forcément refaire tout le local.',
                'options' => [
                    'Interventions' => ['Remplacement comptoir', 'Ajout présentoirs', 'Optimisation rangement', 'Habillage mural', 'Zone promotion', 'Zone conseil'],
                    'Approche' => ['Rénovation légère', 'Rénovation partielle', 'Rénovation complète'],
                    'Contraintes' => ['Travail par étapes', 'Maintien activité', 'Pose sur devis'],
                ],
            ],
        ];
    }
}
