<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\ShowroomActivity;
use Illuminate\Database\Seeder;

class ShowroomRestaurantProductSeeder extends Seeder
{
    public function run(): void
    {
        $this->call(ShowroomActivitySeeder::class);

        $activities = ShowroomActivity::whereIn('slug', $this->activitySlugs())
            ->get()
            ->keyBy('slug');

        foreach ($this->products() as $index => $item) {
            $quoteOnly = $item['type'] !== 'commandable';

            $product = Product::updateOrCreate(
                ['slug' => $item['slug']],
                [
                    'category_id' => null,
                    'room_id' => null,
                    'product_type_id' => null,
                    'primary_collection_id' => null,
                    'title' => $item['title'],
                    'price_millimes' => $this->price($item['price'] ?? null),
                    'compare_at_millimes' => $this->price($item['compare_at'] ?? null),
                    'stock' => $quoteOnly ? 0 : 10,
                    'sku' => null,
                    'brand' => null,
                    'sale_mode' => $quoteOnly ? 'sur_mesure' : 'catalog',
                    'quote_only' => $quoteOnly,
                    'is_starting_price' => (bool) ($item['starting_price'] ?? false),
                    'is_customizable' => $quoteOnly || !empty($item['options']),
                    'showroom_badge' => $item['badge'],
                    'main_image' => null,
                    'material_summary' => $item['materials'],
                    'dimension_summary' => $item['dimensions'],
                    'availability_label' => $item['availability'],
                    'delivery_note' => $item['delivery'],
                    'finish_summary' => $item['finishes'],
                    'short_description' => $item['short_description'],
                    'long_description' => $item['long_description'],
                    'attributes' => null,
                    'custom_options' => $item['options'],
                    'is_active' => true,
                ]
            );

            $payload = [];
            foreach ($item['activities'] as $activitySlug) {
                if (!$activities->has($activitySlug)) {
                    continue;
                }

                $payload[$activities[$activitySlug]->id] = [
                    'sort_order' => $activitySlug === 'restaurants-cafes-fast-foods' ? $index + 1 : 1000 + $index,
                ];
            }

            $product->showroomActivities()->sync($payload);
            $product->images()->delete();
        }
    }

    private function price(?int $dinars): ?int
    {
        return $dinars === null ? null : $dinars * 1000;
    }

    /**
     * @return array<int, string>
     */
    private function activitySlugs(): array
    {
        return [
            'restaurants-cafes-fast-foods',
            'patisseries-boulangeries',
        ];
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function products(): array
    {
        return [
            [
                'title' => 'Comptoir restaurant sur mesure',
                'slug' => 'comptoir-restaurant-sur-mesure',
                'type' => 'quote',
                'badge' => 'Sur mesure, Pro',
                'price' => null,
                'compare_at' => null,
                'starting_price' => false,
                'availability' => 'Sur commande',
                'delivery' => 'Livraison et pose sur devis',
                'activities' => ['restaurants-cafes-fast-foods'],
                'materials' => 'MDF, bois, métal, aluminium, stratifié',
                'dimensions' => 'Sur mesure',
                'finishes' => 'Bois naturel, noir mat, blanc, RAL au choix',
                'short_description' => 'Comptoir d’accueil, de caisse ou de service fabriqué sur mesure pour restaurant, café ou fast-food.',
                'long_description' => 'Ce comptoir est conçu pour structurer l’espace d’accueil, de commande ou d’encaissement d’un restaurant, café ou fast-food. Maison216 peut adapter les dimensions, les rangements, la façade, le plan de travail, les passages câbles et l’intégration du logo selon la configuration du local.',
                'options' => [
                    'Dimensions' => ['Sur mesure'],
                    'Usage' => ['Accueil', 'Caisse', 'Commande', 'Service', 'Click & collect'],
                    'Options' => ['Rangements', 'Passe-câbles', 'Logo en façade', 'LED', 'Plan de travail renforcé', 'Habillage métal'],
                    'Finitions' => ['Bois naturel', 'Noir mat', 'Blanc', 'RAL au choix'],
                ],
            ],
            [
                'title' => 'Comptoir fast-food compact',
                'slug' => 'comptoir-fast-food-compact',
                'type' => 'commandable',
                'badge' => 'Standard, Pro',
                'price' => 1350,
                'compare_at' => 1590,
                'starting_price' => false,
                'availability' => 'Sur commande',
                'delivery' => 'Grand Tunis, pose sur devis',
                'activities' => ['restaurants-cafes-fast-foods'],
                'materials' => 'MDF, stratifié, métal',
                'dimensions' => '160 x 65 x 110 cm',
                'finishes' => 'Noir mat, blanc, bois clair',
                'short_description' => 'Comptoir compact pour fast-food, snack ou petit point de vente alimentaire.',
                'long_description' => 'Ce comptoir compact est adapté aux petits restaurants, snacks, sandwicheries et points de vente à emporter. Il permet d’organiser une zone de caisse ou de commande claire, avec rangements intérieurs et façade professionnelle.',
                'options' => [
                    'Dimensions' => ['160 x 65 x 110 cm'],
                    'Finitions' => ['Noir mat', 'Blanc', 'Bois clair'],
                    'Options' => ['Rangement intérieur', 'Passe-câbles', 'Espace caisse', 'Façade personnalisable'],
                ],
            ],
            [
                'title' => 'Bar café sur mesure',
                'slug' => 'bar-cafe-sur-mesure',
                'type' => 'quote',
                'badge' => 'Sur mesure, Premium, Pro',
                'price' => null,
                'compare_at' => null,
                'starting_price' => false,
                'availability' => 'Sur commande',
                'delivery' => 'Livraison et pose sur devis',
                'activities' => ['restaurants-cafes-fast-foods'],
                'materials' => 'Bois, MDF, métal, aluminium, stratifié',
                'dimensions' => 'Sur mesure',
                'finishes' => 'Bois foncé, bois clair, noir, marbre imitation, RAL au choix',
                'short_description' => 'Bar café fabriqué sur mesure pour cafés, restaurants, salons de thé et espaces de service.',
                'long_description' => 'Le bar café est un élément central dans l’identité d’un café ou restaurant. Maison216 peut concevoir et fabriquer un bar adapté au flux de service, à l’emplacement des machines, aux rangements, à la zone caisse et à l’ambiance du lieu.',
                'options' => [
                    'Dimensions' => ['Sur mesure'],
                    'Usage' => ['Café', 'Salon de thé', 'Restaurant', 'Bar à jus', 'Coffee shop'],
                    'Options' => ['Espace machine café', 'Rangements', 'Éclairage LED', 'Plan de travail renforcé', 'Habillage façade', 'Logo'],
                    'Finitions' => ['Bois foncé', 'Bois clair', 'Noir', 'Marbre imitation', 'RAL au choix'],
                ],
            ],
            [
                'title' => 'Meuble arrière-bar',
                'slug' => 'meuble-arriere-bar',
                'type' => 'quote',
                'badge' => 'Sur mesure, Pro',
                'price' => null,
                'compare_at' => null,
                'starting_price' => false,
                'availability' => 'Sur commande',
                'delivery' => 'Livraison et pose sur devis',
                'activities' => ['restaurants-cafes-fast-foods'],
                'materials' => 'MDF, bois, métal, verre, LED optionnel',
                'dimensions' => 'Sur mesure',
                'finishes' => 'Bois clair, bois foncé, noir mat, blanc, RAL au choix',
                'short_description' => 'Meuble arrière-bar pour organiser les machines, produits, verres, accessoires et éléments de service.',
                'long_description' => 'Ce meuble arrière-bar permet de structurer l’espace derrière le comptoir : rangement, exposition, préparation, stockage léger et mise en valeur des produits. Il peut intégrer des niches, étagères, portes, tiroirs, éclairage ou zones dédiées aux machines.',
                'options' => [
                    'Dimensions' => ['Sur mesure'],
                    'Configuration' => ['Étagères ouvertes', 'Placards', 'Tiroirs', 'Niches', 'Mixte'],
                    'Options' => ['LED', 'Étagères verre', 'Bandeau logo', 'Zone machine', 'Rangement verres', 'Serrures'],
                    'Finitions' => ['Bois clair', 'Bois foncé', 'Noir mat', 'Blanc', 'RAL au choix'],
                ],
            ],
            [
                'title' => 'Banquette restaurant sur mesure',
                'slug' => 'banquette-restaurant-sur-mesure',
                'type' => 'quote',
                'badge' => 'Sur mesure, Pro',
                'price' => null,
                'compare_at' => null,
                'starting_price' => false,
                'availability' => 'Sur commande',
                'delivery' => 'Livraison et pose sur devis',
                'activities' => ['restaurants-cafes-fast-foods'],
                'materials' => 'Bois, MDF, métal, tissu ou simili cuir selon projet',
                'dimensions' => 'Sur mesure',
                'finishes' => 'Bois, tissu, simili cuir, couleur au choix',
                'short_description' => 'Banquette sur mesure pour optimiser les places assises dans un restaurant, café ou salon de thé.',
                'long_description' => 'La banquette permet de créer plus de places assises tout en donnant une identité forte à l’espace. Elle peut être fabriquée selon la longueur du mur, le style du restaurant, la hauteur souhaitée et le niveau de confort recherché.',
                'options' => [
                    'Dimensions' => ['Sur mesure'],
                    'Forme' => ['Droite', 'En L', 'En U', 'Angle'],
                    'Options' => ['Dossier rembourré', 'Assise rembourrée', 'Rangement sous assise', 'Structure bois', 'Structure métal'],
                    'Revêtement' => ['Tissu', 'Simili cuir', 'Couleur au choix'],
                ],
            ],
            [
                'title' => 'Table restaurant bois métal',
                'slug' => 'table-restaurant-bois-metal',
                'type' => 'commandable',
                'badge' => 'Standard, Pro',
                'price' => 280,
                'compare_at' => 340,
                'starting_price' => false,
                'availability' => 'Sur commande',
                'delivery' => 'Grand Tunis',
                'activities' => ['restaurants-cafes-fast-foods'],
                'materials' => 'Plateau bois, structure métal',
                'dimensions' => '70 x 70 x 75 cm',
                'finishes' => 'Bois clair, bois foncé, noir mat',
                'short_description' => 'Table carrée pour restaurant, café ou fast-food avec plateau bois et structure métal.',
                'long_description' => 'Cette table est adaptée aux restaurants, cafés, snacks et espaces de restauration. Sa structure métal assure une bonne résistance, tandis que le plateau bois apporte un style chaleureux et professionnel.',
                'options' => [
                    'Dimensions' => ['70 x 70 cm', '80 x 80 cm', '120 x 70 cm'],
                    'Finitions plateau' => ['Bois clair', 'Bois foncé', 'Noir'],
                    'Structure' => ['Métal noir', 'Métal blanc'],
                    'Options' => ['Plateau renforcé', 'Coins arrondis'],
                ],
            ],
            [
                'title' => 'Mange-debout bois métal',
                'slug' => 'mange-debout-bois-metal',
                'type' => 'commandable',
                'badge' => 'Standard, Pro',
                'price' => 390,
                'compare_at' => 460,
                'starting_price' => false,
                'availability' => 'Sur commande',
                'delivery' => 'Grand Tunis',
                'activities' => ['restaurants-cafes-fast-foods'],
                'materials' => 'Bois, métal',
                'dimensions' => '120 x 50 x 105 cm',
                'finishes' => 'Bois clair, bois foncé, noir mat',
                'short_description' => 'Mange-debout pour café, snack, terrasse ou espace d’attente rapide.',
                'long_description' => 'Ce mange-debout permet de créer une zone de consommation rapide, pratique pour les cafés, fast-foods, snacks et petits espaces. Il convient aussi aux terrasses et aux zones proches du comptoir.',
                'options' => [
                    'Dimensions' => ['100 x 50 x 105 cm', '120 x 50 x 105 cm', '150 x 60 x 105 cm'],
                    'Finitions' => ['Bois clair', 'Bois foncé', 'Noir mat'],
                    'Options' => ['Repose-pieds métal', 'Plateau renforcé', 'Coins arrondis'],
                ],
            ],
            [
                'title' => 'Meuble caisse restaurant',
                'slug' => 'meuble-caisse-restaurant',
                'type' => 'commandable',
                'badge' => 'Standard, Pro',
                'price' => 620,
                'compare_at' => 740,
                'starting_price' => false,
                'availability' => 'Sur commande',
                'delivery' => 'Grand Tunis, pose sur devis',
                'activities' => ['restaurants-cafes-fast-foods'],
                'materials' => 'MDF, bois mélaminé, métal',
                'dimensions' => '90 x 55 x 100 cm',
                'finishes' => 'Noir mat, bois clair, blanc',
                'short_description' => 'Meuble caisse compact pour restaurant, café, snack ou point de vente à emporter.',
                'long_description' => 'Ce meuble caisse permet d’installer une caisse, un terminal de paiement, une imprimante ticket et quelques rangements dans un format compact. Il convient aux petits restaurants, snacks et cafés.',
                'options' => [
                    'Dimensions' => ['90 cm', '120 cm'],
                    'Finitions' => ['Noir mat', 'Bois clair', 'Blanc'],
                    'Options' => ['Passe-câbles', 'Tiroir caisse', 'Rangement sacs', 'Étagère intérieure'],
                ],
            ],
            [
                'title' => 'Claustra séparation restaurant',
                'slug' => 'claustra-separation-restaurant',
                'type' => 'commandable',
                'badge' => 'Standard, Déco',
                'price' => 480,
                'compare_at' => 590,
                'starting_price' => false,
                'availability' => 'Sur commande',
                'delivery' => 'Grand Tunis, pose sur devis',
                'activities' => ['restaurants-cafes-fast-foods'],
                'materials' => 'Bois, MDF, métal',
                'dimensions' => '100 x 220 cm',
                'finishes' => 'Bois naturel, noir, blanc',
                'short_description' => 'Claustra décoratif pour séparer les zones d’un restaurant ou café sans fermer l’espace.',
                'long_description' => 'Ce claustra permet de structurer l’espace d’un restaurant, café ou salon de thé. Il peut servir à séparer une zone d’attente, une salle, une banquette ou un coin plus intime tout en gardant une circulation visuelle.',
                'options' => [
                    'Dimensions' => ['100 x 220 cm', '120 x 220 cm'],
                    'Motifs' => ['Lignes verticales', 'Géométrique', 'Simple'],
                    'Finitions' => ['Bois naturel', 'Noir', 'Blanc'],
                    'Options' => ['Structure métal', 'Fixation sol/plafond'],
                ],
            ],
            [
                'title' => 'Habillage mural restaurant avec logo',
                'slug' => 'habillage-mural-restaurant-logo',
                'type' => 'quote',
                'badge' => 'Sur mesure, Premium, Déco',
                'price' => null,
                'compare_at' => null,
                'starting_price' => false,
                'availability' => 'Sur commande',
                'delivery' => 'Livraison et pose sur devis',
                'activities' => ['restaurants-cafes-fast-foods'],
                'materials' => 'MDF, bois, métal, aluminium, LED',
                'dimensions' => 'Sur mesure',
                'finishes' => 'Bois naturel, noir, blanc, RAL au choix',
                'short_description' => 'Habillage mural décoratif avec logo pour renforcer l’identité visuelle d’un restaurant ou café.',
                'long_description' => 'L’habillage mural transforme un mur simple en véritable élément d’identité. Il peut intégrer un logo, des panneaux décoratifs, des niches, un éclairage LED, une texture bois ou métal, et s’adapter à l’ambiance du lieu.',
                'options' => [
                    'Dimensions' => ['Sur mesure'],
                    'Options' => ['Logo découpé', 'Logo lumineux', 'LED indirecte', 'Niches', 'Panneaux décoratifs', 'Relief 3D'],
                    'Finitions' => ['Bois naturel', 'Noir', 'Blanc', 'RAL au choix'],
                ],
            ],
            [
                'title' => 'Étagère murale café',
                'slug' => 'etagere-murale-cafe',
                'type' => 'commandable',
                'badge' => 'Standard',
                'price' => 240,
                'compare_at' => 290,
                'starting_price' => false,
                'availability' => 'En stock, sur commande',
                'delivery' => 'Grand Tunis',
                'activities' => ['restaurants-cafes-fast-foods'],
                'materials' => 'Bois, métal',
                'dimensions' => '100 x 25 x 60 cm',
                'finishes' => 'Bois clair, bois foncé, métal noir',
                'short_description' => 'Étagère murale décorative pour café, restaurant, comptoir ou arrière-bar.',
                'long_description' => 'Cette étagère murale permet d’exposer verres, tasses, produits, accessoires ou objets décoratifs dans un café ou restaurant. Elle peut être utilisée derrière un bar, près d’un comptoir ou dans une zone de service.',
                'options' => [
                    'Dimensions' => ['80 cm', '100 cm', '120 cm'],
                    'Finitions' => ['Bois clair', 'Bois foncé', 'Métal noir'],
                    'Options' => ['2 niveaux', '3 niveaux', 'Fixation renforcée'],
                ],
            ],
            [
                'title' => 'Meuble service / desserte restaurant',
                'slug' => 'meuble-service-desserte-restaurant',
                'type' => 'commandable',
                'badge' => 'Standard, Pro',
                'price' => 520,
                'compare_at' => 620,
                'starting_price' => false,
                'availability' => 'Sur commande',
                'delivery' => 'Grand Tunis',
                'activities' => ['restaurants-cafes-fast-foods'],
                'materials' => 'MDF, bois mélaminé, métal',
                'dimensions' => '100 x 45 x 90 cm',
                'finishes' => 'Bois clair, noir, blanc',
                'short_description' => 'Meuble de service pour ranger couverts, serviettes, menus, accessoires ou consommables.',
                'long_description' => 'Ce meuble de service permet au personnel d’avoir les éléments nécessaires à portée de main : couverts, serviettes, menus, consommables, verres ou accessoires. Il peut être utilisé en salle, près du comptoir ou dans une zone de service.',
                'options' => [
                    'Dimensions' => ['100 x 45 x 90 cm', '120 x 45 x 90 cm'],
                    'Finitions' => ['Bois clair', 'Noir', 'Blanc'],
                    'Options' => ['Portes', 'Tiroirs', 'Étagères ouvertes', 'Roulettes'],
                ],
            ],
            [
                'title' => 'Meuble poubelle intégrée fast-food',
                'slug' => 'meuble-poubelle-integree-fast-food',
                'type' => 'commandable',
                'badge' => 'Standard, Pro',
                'price' => 450,
                'compare_at' => 540,
                'starting_price' => false,
                'availability' => 'Sur commande',
                'delivery' => 'Grand Tunis',
                'activities' => ['restaurants-cafes-fast-foods'],
                'materials' => 'MDF stratifié, métal',
                'dimensions' => '60 x 45 x 100 cm',
                'finishes' => 'Noir, blanc, gris',
                'short_description' => 'Meuble poubelle intégré pour fast-food, snack, café ou espace de restauration rapide.',
                'long_description' => 'Ce meuble permet d’intégrer une poubelle dans un habillage propre et professionnel. Il est utile dans les fast-foods, snacks, cafés et zones de consommation rapide pour garder l’espace plus organisé et plus esthétique.',
                'options' => [
                    'Dimensions' => ['60 x 45 x 100 cm', '80 x 45 x 100 cm'],
                    'Finitions' => ['Noir', 'Blanc', 'Gris'],
                    'Options' => ['Trappe supérieure', 'Porte frontale', 'Support plateau', 'Signalétique tri'],
                ],
            ],
            [
                'title' => 'Présentoir menu / comptoir',
                'slug' => 'presentoir-menu-comptoir',
                'type' => 'commandable',
                'badge' => 'Standard',
                'price' => 95,
                'compare_at' => 120,
                'starting_price' => false,
                'availability' => 'En stock, sur commande',
                'delivery' => 'Grand Tunis',
                'activities' => ['restaurants-cafes-fast-foods'],
                'materials' => 'Bois, MDF, plexi optionnel',
                'dimensions' => '30 x 15 x 40 cm',
                'finishes' => 'Bois clair, noir, blanc',
                'short_description' => 'Petit présentoir à poser sur comptoir pour menu, flyers, promotions ou QR code.',
                'long_description' => 'Ce présentoir compact peut être placé sur un comptoir, une caisse ou une table d’accueil. Il permet d’afficher un menu, une promotion, un QR code, une carte de fidélité ou un support de communication.',
                'options' => [
                    'Dimensions' => ['30 x 15 x 40 cm', '40 x 20 x 50 cm'],
                    'Finitions' => ['Bois clair', 'Noir', 'Blanc'],
                    'Options' => ['Support QR code', 'Bandeau logo', 'Plexi protection'],
                ],
            ],
            [
                'title' => 'Support menu mural',
                'slug' => 'support-menu-mural-restaurant',
                'type' => 'commandable',
                'badge' => 'Standard, Déco',
                'price' => 180,
                'compare_at' => 220,
                'starting_price' => false,
                'availability' => 'Sur commande',
                'delivery' => 'Grand Tunis',
                'activities' => ['restaurants-cafes-fast-foods'],
                'materials' => 'Bois, MDF, métal',
                'dimensions' => '80 x 60 cm',
                'finishes' => 'Noir mat, bois clair, blanc',
                'short_description' => 'Support mural pour afficher un menu, une carte, des prix ou une sélection de produits.',
                'long_description' => 'Ce support mural est adapté aux cafés, snacks, fast-foods et restaurants qui souhaitent afficher leur menu de façon propre et professionnelle. Il peut servir pour les cartes imprimées, les QR codes ou les offres du jour.',
                'options' => [
                    'Dimensions' => ['80 x 60 cm', '100 x 70 cm', '120 x 80 cm'],
                    'Finitions' => ['Noir mat', 'Bois clair', 'Blanc'],
                    'Options' => ['Support QR code', 'Bandeau logo', 'Cadre métal'],
                ],
            ],
            [
                'title' => 'Présentoir pâtisserie sec',
                'slug' => 'presentoir-patisserie-sec',
                'type' => 'commandable',
                'badge' => 'Standard, Pro',
                'price' => 690,
                'compare_at' => 820,
                'starting_price' => false,
                'availability' => 'Sur commande',
                'delivery' => 'Grand Tunis, pose sur devis',
                'activities' => ['restaurants-cafes-fast-foods', 'patisseries-boulangeries'],
                'materials' => 'MDF, bois, verre, plexi',
                'dimensions' => '100 x 45 x 120 cm',
                'finishes' => 'Blanc, bois clair, noir',
                'short_description' => 'Présentoir sec pour viennoiseries, gâteaux emballés, biscuits ou produits à emporter.',
                'long_description' => 'Ce présentoir est adapté aux cafés, snacks, pâtisseries et espaces de vente à emporter. Il permet d’exposer des produits secs ou emballés de façon visible et propre, à proximité du comptoir ou de la zone caisse.',
                'options' => [
                    'Dimensions' => ['100 x 45 x 120 cm', '120 x 50 x 130 cm'],
                    'Finitions' => ['Blanc', 'Bois clair', 'Noir'],
                    'Options' => ['Protection plexi', 'Étagères inclinées', 'Bandeau logo'],
                ],
            ],
            [
                'title' => 'Étagère épices / condiments',
                'slug' => 'etagere-epices-condiments-restaurant',
                'type' => 'commandable',
                'badge' => 'Standard',
                'price' => 160,
                'compare_at' => 190,
                'starting_price' => false,
                'availability' => 'En stock, sur commande',
                'delivery' => 'Grand Tunis',
                'activities' => ['restaurants-cafes-fast-foods'],
                'materials' => 'Bois, métal',
                'dimensions' => '80 x 15 x 50 cm',
                'finishes' => 'Bois clair, noir, blanc',
                'short_description' => 'Étagère murale compacte pour épices, sauces, condiments ou petits accessoires de service.',
                'long_description' => 'Cette étagère permet de ranger ou présenter des condiments, sauces, épices, accessoires café ou petits produits de service. Elle peut être installée derrière un comptoir, dans une zone préparation ou près d’un espace self-service.',
                'options' => [
                    'Dimensions' => ['60 cm', '80 cm', '100 cm'],
                    'Finitions' => ['Bois clair', 'Noir', 'Blanc'],
                    'Options' => ['2 niveaux', '3 niveaux', 'Barre de retenue métal'],
                ],
            ],
            [
                'title' => 'Porte-menu extérieur sur pied',
                'slug' => 'porte-menu-exterieur-sur-pied',
                'type' => 'commandable',
                'badge' => 'Standard, Extérieur',
                'price' => 260,
                'compare_at' => 320,
                'starting_price' => false,
                'availability' => 'Sur commande',
                'delivery' => 'Grand Tunis',
                'activities' => ['restaurants-cafes-fast-foods'],
                'materials' => 'Métal, bois, plexi',
                'dimensions' => '50 x 120 cm',
                'finishes' => 'Noir mat, bois clair, blanc',
                'short_description' => 'Porte-menu extérieur sur pied pour afficher la carte, les offres ou les promotions devant le local.',
                'long_description' => 'Ce porte-menu sur pied permet d’attirer l’attention des passants et de présenter la carte ou les offres du jour. Il convient aux restaurants, cafés, salons de thé, snacks et commerces alimentaires.',
                'options' => [
                    'Dimensions' => ['50 x 120 cm', '60 x 140 cm'],
                    'Finitions' => ['Noir mat', 'Bois clair', 'Blanc'],
                    'Options' => ['Support affiche', 'Support QR code', 'Logo', 'Plexi protection'],
                ],
            ],
            [
                'title' => 'Pack ouverture fast-food',
                'slug' => 'pack-ouverture-fast-food',
                'type' => 'quote',
                'badge' => 'Pack, Sur mesure, Pro',
                'price' => null,
                'compare_at' => null,
                'starting_price' => false,
                'availability' => 'Sur commande',
                'delivery' => 'Livraison et pose sur devis',
                'activities' => ['restaurants-cafes-fast-foods'],
                'materials' => 'MDF, bois, métal, aluminium selon projet',
                'dimensions' => 'Selon local',
                'finishes' => 'Selon identité visuelle',
                'short_description' => 'Pack d’aménagement pour ouvrir un fast-food, snack ou point de vente à emporter.',
                'long_description' => 'Le Pack ouverture fast-food regroupe les éléments visibles essentiels pour lancer un espace de restauration rapide : comptoir de commande, meuble caisse, habillage mural, supports menu, meuble service et éléments de rangement. Le pack est adapté selon la surface, le concept, le flux client et le budget.',
                'options' => [
                    'Inclus' => ['Comptoir de commande', 'Meuble caisse', 'Habillage mural', 'Support menu', 'Meuble service'],
                    'Options' => ['Arrière-comptoir', 'LED', 'Logo', 'Porte-menu extérieur', 'Meuble poubelle intégrée', 'Pose complète'],
                    'Adaptation' => ['Petit local', 'Local moyen', 'Sur mesure complet'],
                ],
            ],
            [
                'title' => 'Pack ouverture café / coffee shop',
                'slug' => 'pack-ouverture-cafe-coffee-shop',
                'type' => 'quote',
                'badge' => 'Pack, Premium, Sur mesure',
                'price' => null,
                'compare_at' => null,
                'starting_price' => false,
                'availability' => 'Sur commande',
                'delivery' => 'Livraison et pose sur devis',
                'activities' => ['restaurants-cafes-fast-foods'],
                'materials' => 'Bois, MDF, métal, aluminium, verre, LED selon projet',
                'dimensions' => 'Selon local',
                'finishes' => 'Selon concept et identité visuelle',
                'short_description' => 'Solution d’aménagement pour ouvrir un café, coffee shop ou salon de thé avec comptoir, bar et mobilier adapté.',
                'long_description' => 'Ce pack est pensé pour les cafés, coffee shops et salons de thé qui veulent un espace cohérent dès l’ouverture. Il peut inclure un bar café, un arrière-bar, des étagères murales, un meuble caisse, des mange-debout, des tables et un habillage mural avec logo.',
                'options' => [
                    'Inclus' => ['Bar café', 'Arrière-bar', 'Étagères murales', 'Meuble caisse', 'Tables ou mange-debout'],
                    'Options' => ['Logo mural', 'LED', 'Banquette', 'Claustra', 'Porte-menu extérieur', 'Meuble service'],
                    'Style' => ['Industriel', 'Minimaliste', 'Bois chaleureux', 'Premium'],
                ],
            ],
            [
                'title' => 'Pack rénovation restaurant',
                'slug' => 'pack-renovation-restaurant',
                'type' => 'quote',
                'badge' => 'Pack, Sur mesure, Pro',
                'price' => null,
                'compare_at' => null,
                'starting_price' => false,
                'availability' => 'Sur commande',
                'delivery' => 'Livraison et pose sur devis',
                'activities' => ['restaurants-cafes-fast-foods'],
                'materials' => 'Selon projet',
                'dimensions' => 'Selon local',
                'finishes' => 'Selon identité existante',
                'short_description' => 'Pack pour moderniser un restaurant ou café existant sans refaire tout le local.',
                'long_description' => 'Ce pack est destiné aux restaurants, cafés et snacks qui veulent améliorer leur image ou leur fonctionnement par étapes. Maison216 peut intervenir sur le comptoir, les banquettes, l’habillage mural, le mobilier de salle, les séparations ou les éléments de rangement.',
                'options' => [
                    'Interventions' => ['Remplacement comptoir', 'Ajout banquettes', 'Habillage mural', 'Nouveau mobilier', 'Claustras', 'Meuble service'],
                    'Approche' => ['Rénovation légère', 'Rénovation partielle', 'Rénovation complète'],
                    'Contraintes' => ['Travail par étapes', 'Maintien activité', 'Pose sur devis'],
                ],
            ],
        ];
    }
}
