<?php

return [
    'rooms' => [
        [
            'code' => 'chambre_adulte',
            'name' => 'Chambre adulte',
            'slug' => 'chambre-adulte',
            'tagline' => 'Lits, dressings, commodes et compositions pour la chambre principale.',
            'description' => 'Univers principal pour la chambre adulte, les modules séparés et les futures compositions guidées.',
            'position' => 10,
        ],
        [
            'code' => 'chambre_enfant',
            'name' => 'Chambre enfant',
            'slug' => 'chambre-enfant',
            'tagline' => 'Lits enfant, rangements et ensembles pour chambres junior.',
            'description' => 'Univers dédié aux lits enfant, rangements junior, bureaux enfant et chambres complètes.',
            'position' => 20,
        ],
        [
            'code' => 'salon_sejour',
            'name' => 'Salon & sejour',
            'slug' => 'salon-sejour',
            'tagline' => 'Canapés, meubles TV, tables basses et bibliothèques.',
            'description' => 'Univers salon pour les assises, le séjour, les bibliothèques et les compositions salon.',
            'position' => 30,
        ],
        [
            'code' => 'salle_a_manger',
            'name' => 'Salle a manger',
            'slug' => 'salle-a-manger',
            'tagline' => 'Tables, chaises, bahuts et salles a manger complètes.',
            'description' => 'Univers salle à manger centré sur les tables, assises, buffets et compositions complètes.',
            'position' => 40,
        ],
        [
            'code' => 'cuisine_rangement',
            'name' => 'Cuisine & rangement',
            'slug' => 'cuisine-rangement',
            'tagline' => 'Modules cuisine, colonnes, plans de travail et cuisine complète.',
            'description' => 'Univers cuisine modulaire, rangement et futurs flux de composition guidée.',
            'position' => 50,
        ],
        [
            'code' => 'bureau',
            'name' => 'Bureau',
            'slug' => 'bureau',
            'tagline' => 'Bureaux, rangements et mobilier de travail.',
            'description' => 'Univers bureau pour le travail à domicile, la direction et les rangements professionnels.',
            'position' => 60,
        ],
        [
            'code' => 'entree_rangement',
            'name' => 'Entree & rangement',
            'slug' => 'entree-rangement',
            'tagline' => 'Consoles, penderies, bancs et rangements d’entrée.',
            'description' => 'Univers entrée et rangement pour les zones de passage, le vestiaire et les solutions chaussures.',
            'position' => 70,
        ],
        [
            'code' => 'salle_de_bain',
            'name' => 'Salle de bain',
            'slug' => 'salle-de-bain',
            'tagline' => 'Meubles vasque, colonnes, miroirs et rangements salle de bain.',
            'description' => 'Univers salle de bain pour les meubles sous-vasque, colonnes, miroirs et ensembles.',
            'position' => 80,
        ],
        [
            'code' => 'exterieur_jardin',
            'name' => 'Exterieur & jardin',
            'slug' => 'exterieur-jardin',
            'tagline' => 'Jardin, balcon, terrasse et mobilier extérieur.',
            'description' => 'Univers extérieur pour tables, salons de jardin, parasols, barbecue et rangement outdoor.',
            'position' => 90,
        ],
        [
            'code' => 'sur_mesure_travaux',
            'name' => 'Sur mesure & travaux',
            'slug' => 'sur-mesure-travaux',
            'tagline' => 'Bois, aluminium, ferronnerie et projets accompagnés.',
            'description' => 'Univers service pour les demandes de devis, rendez-vous et projets d’atelier sur mesure.',
            'position' => 100,
        ],
    ],

    'product_types' => [
        ['code' => 'lit', 'name' => 'Lits', 'slug' => 'lits', 'short_label' => 'Lits', 'room_code' => 'chambre_adulte', 'position' => 10],
        ['code' => 'lit_superpose', 'name' => 'Lits superposes', 'slug' => 'lits-superposes', 'short_label' => 'Superposes', 'room_code' => 'chambre_enfant', 'position' => 20],
        ['code' => 'lit_gigogne', 'name' => 'Lits gigognes', 'slug' => 'lits-gigognes', 'short_label' => 'Gigognes', 'room_code' => 'chambre_enfant', 'position' => 30],
        ['code' => 'table_de_nuit', 'name' => 'Tables de nuit', 'slug' => 'tables-de-nuit', 'short_label' => 'Chevets', 'room_code' => 'chambre_adulte', 'position' => 40],
        ['code' => 'armoire', 'name' => 'Armoires', 'slug' => 'armoires', 'short_label' => 'Armoires', 'room_code' => 'chambre_adulte', 'position' => 50],
        ['code' => 'dressing', 'name' => 'Dressings', 'slug' => 'dressings', 'short_label' => 'Dressings', 'room_code' => 'chambre_adulte', 'position' => 60],
        ['code' => 'penderie', 'name' => 'Penderies', 'slug' => 'penderies', 'short_label' => 'Penderies', 'room_code' => 'entree_rangement', 'position' => 70],
        ['code' => 'commode', 'name' => 'Commodes', 'slug' => 'commodes', 'short_label' => 'Commodes', 'room_code' => 'chambre_adulte', 'position' => 80],
        ['code' => 'coiffeuse', 'name' => 'Coiffeuses', 'slug' => 'coiffeuses', 'short_label' => 'Coiffeuses', 'room_code' => 'chambre_adulte', 'position' => 90],
        ['code' => 'canape', 'name' => 'Canapes', 'slug' => 'canapes', 'short_label' => 'Canapés', 'room_code' => 'salon_sejour', 'position' => 100],
        ['code' => 'fauteuil', 'name' => 'Fauteuils', 'slug' => 'fauteuils', 'short_label' => 'Fauteuils', 'room_code' => 'salon_sejour', 'position' => 110],
        ['code' => 'table_basse', 'name' => 'Tables basses', 'slug' => 'tables-basses', 'short_label' => 'Tables basses', 'room_code' => 'salon_sejour', 'position' => 120],
        ['code' => 'meuble_tv', 'name' => 'Meubles TV', 'slug' => 'meubles-tv', 'short_label' => 'Meubles TV', 'room_code' => 'salon_sejour', 'position' => 130],
        ['code' => 'bibliotheque', 'name' => 'Bibliotheques', 'slug' => 'bibliotheques', 'short_label' => 'Bibliothèques', 'room_code' => 'salon_sejour', 'position' => 140],
        ['code' => 'etagere', 'name' => 'Etageres', 'slug' => 'etageres', 'short_label' => 'Étagères', 'room_code' => 'salon_sejour', 'position' => 150],
        ['code' => 'buffet', 'name' => 'Buffets', 'slug' => 'buffets', 'short_label' => 'Buffets', 'room_code' => 'salle_a_manger', 'position' => 160],
        ['code' => 'bahut', 'name' => 'Bahuts', 'slug' => 'bahuts', 'short_label' => 'Bahuts', 'room_code' => 'salle_a_manger', 'position' => 170],
        ['code' => 'vaisselier', 'name' => 'Vaisseliers', 'slug' => 'vaisseliers', 'short_label' => 'Vaisseliers', 'room_code' => 'salle_a_manger', 'position' => 180],
        ['code' => 'table_a_manger', 'name' => 'Tables a manger', 'slug' => 'tables-a-manger', 'short_label' => 'Tables', 'room_code' => 'salle_a_manger', 'position' => 190],
        ['code' => 'chaise', 'name' => 'Chaises', 'slug' => 'chaises', 'short_label' => 'Chaises', 'room_code' => 'salle_a_manger', 'position' => 200],
        ['code' => 'banc', 'name' => 'Bancs', 'slug' => 'bancs', 'short_label' => 'Bancs', 'room_code' => 'salle_a_manger', 'position' => 210],
        ['code' => 'bar', 'name' => 'Meubles de bar', 'slug' => 'meubles-de-bar', 'short_label' => 'Bars', 'room_code' => 'salle_a_manger', 'position' => 220],
        ['code' => 'tabouret_haut', 'name' => 'Tabourets hauts', 'slug' => 'tabourets-hauts', 'short_label' => 'Tabourets', 'room_code' => 'salle_a_manger', 'position' => 230],
        ['code' => 'meuble_bas_cuisine', 'name' => 'Meubles bas cuisine', 'slug' => 'meubles-bas-cuisine', 'short_label' => 'Meubles bas', 'room_code' => 'cuisine_rangement', 'position' => 240],
        ['code' => 'meuble_haut_cuisine', 'name' => 'Meubles hauts cuisine', 'slug' => 'meubles-hauts-cuisine', 'short_label' => 'Meubles hauts', 'room_code' => 'cuisine_rangement', 'position' => 250],
        ['code' => 'colonne_cuisine', 'name' => 'Colonnes cuisine', 'slug' => 'colonnes-cuisine', 'short_label' => 'Colonnes', 'room_code' => 'cuisine_rangement', 'position' => 260],
        ['code' => 'plan_de_travail', 'name' => 'Plans de travail', 'slug' => 'plans-de-travail', 'short_label' => 'Plans', 'room_code' => 'cuisine_rangement', 'position' => 270],
        ['code' => 'bureau', 'name' => 'Bureaux', 'slug' => 'bureaux', 'short_label' => 'Bureaux', 'room_code' => 'bureau', 'position' => 280],
        ['code' => 'rangement_bureau', 'name' => 'Rangements de bureau', 'slug' => 'rangements-bureau', 'short_label' => 'Rangements', 'room_code' => 'bureau', 'position' => 290],
        ['code' => 'meuble_entree', 'name' => 'Meubles d entree', 'slug' => 'meubles-entree', 'short_label' => 'Entrée', 'room_code' => 'entree_rangement', 'position' => 300],
        ['code' => 'porte_chaussures', 'name' => 'Portes-chaussures', 'slug' => 'portes-chaussures', 'short_label' => 'Chaussures', 'room_code' => 'entree_rangement', 'position' => 310],
        ['code' => 'console', 'name' => 'Consoles', 'slug' => 'consoles', 'short_label' => 'Consoles', 'room_code' => 'entree_rangement', 'position' => 320],
        ['code' => 'separation', 'name' => 'Separations', 'slug' => 'separations', 'short_label' => 'Séparations', 'room_code' => 'entree_rangement', 'position' => 330],
        ['code' => 'meuble_sous_vasque', 'name' => 'Meubles sous vasque', 'slug' => 'meubles-sous-vasque', 'short_label' => 'Sous-vasque', 'room_code' => 'salle_de_bain', 'position' => 340],
        ['code' => 'colonne_salle_de_bain', 'name' => 'Colonnes salle de bain', 'slug' => 'colonnes-salle-de-bain', 'short_label' => 'Colonnes SDB', 'room_code' => 'salle_de_bain', 'position' => 350],
        ['code' => 'miroir', 'name' => 'Miroirs', 'slug' => 'miroirs', 'short_label' => 'Miroirs', 'room_code' => 'salle_de_bain', 'position' => 360],
        ['code' => 'salon_de_jardin', 'name' => 'Salons de jardin', 'slug' => 'salons-de-jardin', 'short_label' => 'Salons jardin', 'room_code' => 'exterieur_jardin', 'position' => 370],
        ['code' => 'table_de_jardin', 'name' => 'Tables de jardin', 'slug' => 'tables-de-jardin', 'short_label' => 'Tables jardin', 'room_code' => 'exterieur_jardin', 'position' => 380],
        ['code' => 'banc_exterieur', 'name' => 'Bancs exterieur', 'slug' => 'bancs-exterieur', 'short_label' => 'Bancs jardin', 'room_code' => 'exterieur_jardin', 'position' => 390],
        ['code' => 'parasol', 'name' => 'Parasols', 'slug' => 'parasols', 'short_label' => 'Parasols', 'room_code' => 'exterieur_jardin', 'position' => 400],
        ['code' => 'barbecue', 'name' => 'Barbecue & feu', 'slug' => 'barbecue-feu', 'short_label' => 'Barbecue', 'room_code' => 'exterieur_jardin', 'position' => 410],
        ['code' => 'rangement_exterieur', 'name' => 'Rangements exterieur', 'slug' => 'rangements-exterieur', 'short_label' => 'Rangements', 'room_code' => 'exterieur_jardin', 'position' => 420],
    ],
];
