<?php

return [
    [
        'title' => 'Menuiserie bois',
        'path' => 'menuiserie-bois',
        'description' => 'Meubles, rangements et amenagements en bois, du produit pret a commander au projet fabrique sur mesure.',
        'type' => 'quote',
    ],
    [
        'title' => 'Cuisine & Dressing',
        'path' => 'cuisine-dressing',
        'description' => 'Des projets sur mesure pour organiser la cuisine, le dressing, le placard, le meuble TV ou le bureau selon votre espace.',
        'type' => 'quote',
        'children' => [
            ['title' => 'Cuisine sur mesure', 'path' => 'cuisine-dressing/cuisine-sur-mesure', 'description' => 'Concevez une cuisine adaptee a vos dimensions, vos rangements et votre rythme de vie.', 'type' => 'quote'],
            ['title' => 'Dressing sur mesure', 'path' => 'cuisine-dressing/dressing-sur-mesure', 'description' => 'Optimisez vos rangements avec un dressing pense pour vos vetements, accessoires et contraintes de piece.', 'type' => 'quote'],
            ['title' => 'Placard sur mesure', 'path' => 'cuisine-dressing/placard-sur-mesure', 'description' => 'Transformez une niche, un mur ou un couloir en rangement utile, discret et bien integre.', 'type' => 'quote'],
            ['title' => 'Meuble TV sur mesure', 'path' => 'cuisine-dressing/meuble-tv-sur-mesure', 'description' => 'Un meuble TV adapte au mur, aux appareils, aux rangements et au style du salon.', 'type' => 'quote'],
            ['title' => 'Bureau sur mesure', 'path' => 'cuisine-dressing/bureau-sur-mesure', 'description' => 'Amenagez un espace de travail confortable, range et dimensionne pour votre quotidien.', 'type' => 'quote'],
        ],
    ],
    [
        'title' => 'Menuiserie Alu',
        'path' => 'aluminium',
        'description' => 'Fenêtres, portes, vitrines, verrieres, cloisons et cabines de douche realisees selon les contraintes du lieu.',
        'type' => 'quote',
        'children' => [
            ['title' => 'Fenêtre aluminium', 'path' => 'aluminium/fenetre-aluminium', 'description' => 'Des fenetres aluminium pour mieux gerer luminosite, isolation et ouverture.', 'type' => 'quote'],
            ['title' => 'Porte aluminium', 'path' => 'aluminium/porte-aluminium', 'description' => 'Des portes aluminium solides et propres pour maison, local ou espace professionnel.', 'type' => 'quote'],
            ['title' => 'Vitrine magasin', 'path' => 'aluminium/vitrine-magasin', 'description' => 'Des vitrines de magasin concues pour presenter, proteger et valoriser votre activite.', 'type' => 'quote'],
            ['title' => 'Verrière', 'path' => 'aluminium/verriere', 'description' => 'Separez sans fermer avec une verriere adaptee a votre interieur.', 'type' => 'quote'],
            ['title' => 'Cloison aluminium', 'path' => 'aluminium/cloison-aluminium', 'description' => 'Structurez vos espaces avec des cloisons aluminium nettes et durables.', 'type' => 'quote'],
            ['title' => 'Cabine de douche', 'path' => 'aluminium/cabine-de-douche', 'description' => 'Une cabine de douche ajustee aux dimensions de votre salle de bain.', 'type' => 'quote'],
        ],
    ],
    [
        'title' => 'Fabrication métallique',
        'path' => 'fer-metal',
        'description' => 'Portails, pergolas, garde-corps, grilles et escaliers metalliques fabriques pour durer.',
        'type' => 'quote',
        'children' => [
            ['title' => 'Portail fer forge', 'path' => 'fer-metal/portail-fer-forge', 'description' => 'Un portail en fer adapte a votre entree, a votre securite et au style de la facade.', 'type' => 'quote'],
            ['title' => 'Pergola metallique', 'path' => 'fer-metal/pergola-metallique', 'description' => 'Une structure metallique pour proteger et valoriser une terrasse ou un espace exterieur.', 'type' => 'quote'],
            ['title' => 'Garde-corps', 'path' => 'fer-metal/garde-corps', 'description' => 'Des garde-corps solides pour escaliers, balcons, terrasses et mezzanines.', 'type' => 'quote'],
            ['title' => 'Grille de protection', 'path' => 'fer-metal/grille-de-protection', 'description' => 'Des grilles de protection concues selon vos ouvertures et votre niveau de securite.', 'type' => 'quote'],
            ['title' => 'Escalier metallique', 'path' => 'fer-metal/escalier-metallique', 'description' => 'Un escalier metallique dimensionne selon le lieu, l usage et la finition souhaitee.', 'type' => 'quote'],
        ],
    ],
    [
        'title' => 'Meubles',
        'path' => 'meubles',
        'description' => 'Explorez les meubles par piece, par besoin et par type pour trouver plus vite ce qui convient a votre interieur.',
        'type' => 'catalog',
        'children' => [
            [
                'title' => 'Salon & sejour',
                'path' => 'meubles/salon-sejour',
                'description' => 'Canapes, fauteuils, tables basses, meubles TV, buffets, bibliotheques, etageres et bancs.',
                'type' => 'catalog',
                'children' => [
                    ['title' => 'Canapes', 'path' => 'meubles/salon-sejour/canapes', 'description' => 'Des canapes pour structurer le salon et accueillir confortablement.', 'type' => 'catalog'],
                    ['title' => 'Fauteuils', 'path' => 'meubles/salon-sejour/fauteuils', 'description' => 'Des fauteuils pour completer l assise et donner du caractere au sejour.', 'type' => 'catalog'],
                    ['title' => 'Tables basses', 'path' => 'meubles/salon-sejour/tables-basses', 'description' => 'Des tables basses adaptees au salon, au rangement et au style de vie.', 'type' => 'catalog'],
                    ['title' => 'Meubles TV', 'path' => 'meubles/salon-sejour/meubles-tv', 'description' => 'Des meubles TV pour ranger, presenter et organiser le coin multimedia.', 'type' => 'catalog'],
                    ['title' => 'Buffets', 'path' => 'meubles/salon-sejour/buffets', 'description' => 'Des buffets pour ajouter du rangement sans alourdir le sejour.', 'type' => 'catalog'],
                    ['title' => 'Bibliotheques', 'path' => 'meubles/salon-sejour/bibliotheques', 'description' => 'Des bibliotheques pour livres, objets decoratifs et rangements ouverts.', 'type' => 'catalog'],
                    ['title' => 'Etageres', 'path' => 'meubles/salon-sejour/etageres', 'description' => 'Des etageres murales ou posees pour organiser sans perdre de place.', 'type' => 'catalog'],
                    ['title' => 'Bancs', 'path' => 'meubles/salon-sejour/bancs', 'description' => 'Des bancs utiles pour l assise, l entree ou le complement du salon.', 'type' => 'catalog'],
                ],
            ],
            [
                'title' => 'Chambres a coucher',
                'path' => 'meubles/chambres-a-coucher',
                'description' => 'Le hub catalogue pour lits, armoires, dressings, commodes, coiffeuses et meubles de chambre.',
                'type' => 'catalog',
                'children' => [
                    ['title' => 'Chambres adultes', 'path' => 'meubles/chambres-a-coucher/chambres-adultes', 'description' => 'Des chambres adultes completes ou a composer selon votre espace.', 'type' => 'catalog'],
                    ['title' => 'Chambres enfants', 'path' => 'meubles/chambres-a-coucher/chambres-enfants', 'description' => 'Des chambres enfant fonctionnelles pour dormir, ranger et travailler.', 'type' => 'catalog'],
                    [
                        'title' => 'Lits',
                        'path' => 'meubles/chambres-a-coucher/lits',
                        'description' => 'Lits doubles, simples, superposes et tetes de lit pour chaque configuration.',
                        'type' => 'catalog',
                        'children' => [
                            ['title' => 'Lits doubles', 'path' => 'meubles/chambres-a-coucher/lits/lits-doubles', 'description' => 'Des lits doubles pour chambres adultes et suites parentales.', 'type' => 'catalog'],
                            ['title' => 'Lits simples', 'path' => 'meubles/chambres-a-coucher/lits/lits-simples', 'description' => 'Des lits simples pour chambres compactes, enfants ou chambres d amis.', 'type' => 'catalog'],
                            ['title' => 'Lits superposes', 'path' => 'meubles/chambres-a-coucher/lits/lits-superposes', 'description' => 'Des lits superposes pour optimiser la place dans une chambre partagee.', 'type' => 'catalog'],
                            ['title' => 'Tetes de lit', 'path' => 'meubles/chambres-a-coucher/lits/tetes-de-lit', 'description' => 'Des tetes de lit pour completer le couchage et habiller le mur.', 'type' => 'catalog'],
                        ],
                    ],
                    ['title' => 'Armoires', 'path' => 'meubles/chambres-a-coucher/armoires', 'description' => 'Des armoires pour organiser les vetements et le linge de maison.', 'type' => 'catalog'],
                    ['title' => 'Dressings', 'path' => 'meubles/chambres-a-coucher/dressings', 'description' => 'Des dressings catalogue ou points de depart vers un projet sur mesure.', 'type' => 'catalog'],
                    ['title' => 'Commodes', 'path' => 'meubles/chambres-a-coucher/commodes', 'description' => 'Des commodes pour completer les rangements de chambre.', 'type' => 'catalog'],
                    ['title' => 'Coiffeuses', 'path' => 'meubles/chambres-a-coucher/coiffeuses', 'description' => 'Des coiffeuses pour organiser maquillage, accessoires et miroir.', 'type' => 'catalog'],
                    ['title' => 'Bancs de lit', 'path' => 'meubles/chambres-a-coucher/bancs-de-lit', 'description' => 'Des bancs de lit pour ajouter confort et finition a la chambre.', 'type' => 'catalog'],
                ],
            ],
            ['title' => 'Chambre adulte', 'path' => 'meubles/chambre-adulte', 'description' => 'Une page d intention pour choisir ou composer une chambre adulte coherente.', 'type' => 'intent'],
            [
                'title' => 'Chambre enfant',
                'path' => 'meubles/chambre-enfant',
                'description' => 'Une page d intention pour organiser sommeil, rangement et bureau dans une chambre enfant.',
                'type' => 'intent',
                'children' => [
                    ['title' => 'Lits enfants', 'path' => 'meubles/chambre-enfant/lits-enfants', 'description' => 'Des lits adaptes aux chambres enfant et aux petits espaces.', 'type' => 'catalog'],
                    ['title' => 'Bureaux enfants', 'path' => 'meubles/chambre-enfant/bureaux-enfants', 'description' => 'Des bureaux pour apprendre, dessiner et ranger les fournitures.', 'type' => 'catalog'],
                    ['title' => 'Coffres a jouets', 'path' => 'meubles/chambre-enfant/coffres-a-jouets', 'description' => 'Des coffres pour ranger les jouets sans encombrer la piece.', 'type' => 'catalog'],
                    ['title' => 'Bibliotheques enfants', 'path' => 'meubles/chambre-enfant/bibliotheques-enfants', 'description' => 'Des bibliotheques enfant pour livres, jeux et objets du quotidien.', 'type' => 'catalog'],
                ],
            ],
            [
                'title' => 'Salle a manger',
                'path' => 'meubles/salle-a-manger',
                'description' => 'Tables, chaises, buffets et vaisseliers pour recevoir et ranger.',
                'type' => 'catalog',
                'children' => [
                    ['title' => 'Tables a manger', 'path' => 'meubles/salle-a-manger/tables-a-manger', 'description' => 'Des tables a manger pour repas quotidiens et grandes reunions.', 'type' => 'catalog'],
                    ['title' => 'Chaises', 'path' => 'meubles/salle-a-manger/chaises', 'description' => 'Des chaises assorties ou contrastantes pour la salle a manger.', 'type' => 'catalog'],
                    ['title' => 'Buffets', 'path' => 'meubles/salle-a-manger/buffets', 'description' => 'Des buffets pour ranger vaisselle, linge de table et objets utiles.', 'type' => 'catalog'],
                    ['title' => 'Vaisseliers', 'path' => 'meubles/salle-a-manger/vaisseliers', 'description' => 'Des vaisseliers pour exposer et proteger la vaisselle.', 'type' => 'catalog'],
                ],
            ],
            [
                'title' => 'Bureau',
                'path' => 'meubles/bureau',
                'description' => 'Bureaux, caissons et rangements pour travailler avec plus d ordre.',
                'type' => 'catalog',
                'children' => [
                    ['title' => 'Caissons de rangement', 'path' => 'meubles/bureau/caissons-de-rangement', 'description' => 'Des caissons pour documents, fournitures et accessoires de bureau.', 'type' => 'catalog'],
                    ['title' => 'Meubles imprimante', 'path' => 'meubles/bureau/meubles-imprimante', 'description' => 'Des meubles pour imprimante, papier et accessoires techniques.', 'type' => 'catalog'],
                    ['title' => 'Tables de travail', 'path' => 'meubles/bureau/tables-de-travail', 'description' => 'Des tables de travail pour bureau personnel ou professionnel.', 'type' => 'catalog'],
                    ['title' => 'Meubles bureau professionnels', 'path' => 'meubles/bureau/meubles-bureau-professionnels', 'description' => 'Des meubles adaptes aux espaces de travail et bureaux professionnels.', 'type' => 'catalog'],
                ],
            ],
            [
                'title' => 'Cuisine & rangement',
                'path' => 'meubles/cuisine-rangement',
                'description' => 'Elements de rangement, tables de cuisine et placards pour organiser le quotidien.',
                'type' => 'catalog',
                'children' => [
                    ['title' => 'Elements de rangement cuisine', 'path' => 'meubles/cuisine-rangement/elements-de-rangement-cuisine', 'description' => 'Des modules pour mieux ranger ustensiles, provisions et accessoires.', 'type' => 'catalog'],
                    ['title' => 'Tables de cuisine', 'path' => 'meubles/cuisine-rangement/tables-de-cuisine', 'description' => 'Des tables compactes ou familiales pour la cuisine.', 'type' => 'catalog'],
                    ['title' => 'Placards cuisine', 'path' => 'meubles/cuisine-rangement/placards-cuisine', 'description' => 'Des placards de cuisine pour completer ou structurer le rangement.', 'type' => 'catalog'],
                ],
            ],
            [
                'title' => 'Entree & couloir',
                'path' => 'meubles/entree-couloir',
                'description' => 'Meubles d entree, porte-chaussures, bancs, porte-manteaux et miroirs.',
                'type' => 'catalog',
                'children' => [
                    ['title' => 'Meubles d entree', 'path' => 'meubles/entree-couloir/meubles-entree', 'description' => 'Des meubles pour poser, ranger et structurer l entree.', 'type' => 'catalog'],
                    ['title' => 'Porte-chaussures', 'path' => 'meubles/entree-couloir/porte-chaussures', 'description' => 'Des solutions pour ranger les chaussures proprement.', 'type' => 'catalog'],
                    ['title' => 'Bancs d entree', 'path' => 'meubles/entree-couloir/bancs-entree', 'description' => 'Des bancs utiles pour s asseoir, ranger ou habiller le couloir.', 'type' => 'catalog'],
                    ['title' => 'Porte-manteaux', 'path' => 'meubles/entree-couloir/porte-manteaux', 'description' => 'Des porte-manteaux pour garder vestes et sacs accessibles.', 'type' => 'catalog'],
                    ['title' => 'Miroirs', 'path' => 'meubles/entree-couloir/miroirs', 'description' => 'Des miroirs pour agrandir visuellement l entree ou finaliser la piece.', 'type' => 'catalog'],
                ],
            ],
            ['title' => 'Meubles TV', 'path' => 'meubles/meubles-tv', 'description' => 'Tous les meubles TV, du modele pret a commander au projet plus personnalise.', 'type' => 'catalog'],
            [
                'title' => 'Meubles professionnels',
                'path' => 'meubles/meubles-professionnels',
                'description' => 'Mobilier pour bureaux, boutiques, accueils, cafes, restaurants et rangements professionnels.',
                'type' => 'catalog',
                'children' => [
                    ['title' => 'Meubles pour bureaux', 'path' => 'meubles/meubles-professionnels/meubles-pour-bureaux', 'description' => 'Des meubles pour organiser les postes de travail et les espaces pros.', 'type' => 'catalog'],
                    ['title' => 'Meubles pour boutiques', 'path' => 'meubles/meubles-professionnels/meubles-pour-boutiques', 'description' => 'Des meubles pour presenter, ranger et structurer une boutique.', 'type' => 'catalog'],
                    ['title' => 'Comptoirs d accueil', 'path' => 'meubles/meubles-professionnels/comptoirs-accueil', 'description' => 'Des comptoirs pour accueillir, vendre et organiser la reception client.', 'type' => 'quote'],
                    ['title' => 'Presentoirs', 'path' => 'meubles/meubles-professionnels/presentoirs', 'description' => 'Des presentoirs pour mettre en avant vos produits.', 'type' => 'quote'],
                    ['title' => 'Rangements professionnels', 'path' => 'meubles/meubles-professionnels/rangements-professionnels', 'description' => 'Des rangements adaptes aux besoins de stockage professionnel.', 'type' => 'catalog'],
                    ['title' => 'Mobilier cafe / restaurant', 'path' => 'meubles/meubles-professionnels/mobilier-cafe-restaurant', 'description' => 'Du mobilier pour espaces cafe, restaurant et accueil public.', 'type' => 'quote'],
                ],
            ],
        ],
    ],
    [
        'title' => 'Guides',
        'path' => 'guides',
        'description' => 'Des guides pour comprendre les prix, comparer les options et mieux preparer votre achat ou votre projet.',
        'type' => 'guide',
        'children' => [
            ['title' => 'Guide de Prix', 'path' => 'guides/guide-de-prix', 'description' => 'Reperez les facteurs qui influencent le prix d un meuble ou d un projet sur mesure.', 'type' => 'guide'],
            ['title' => 'Conseils', 'path' => 'guides/conseils', 'description' => 'Des conseils simples pour mieux choisir dimensions, rangements, styles et finitions.', 'type' => 'guide'],
        ],
    ],
    [
        'title' => 'Devis',
        'path' => 'devis',
        'description' => 'Envoyez votre besoin, vos dimensions ou vos photos pour recevoir une orientation claire.',
        'type' => 'quote',
    ],
    [
        'title' => 'Contact',
        'path' => 'contact',
        'description' => 'Contactez Maison 216 pour une question, une commande ou un accompagnement.',
        'type' => 'contact',
    ],
];
